from scrapy import Field, Item


class RealEstateFund(Item):
    code = Field()
    name = Field()
    document = Field()
    targetInvestor = Field()
    emittedQuotas = Field()
    mandate = Field()
    sector = Field()
    currentPrice = Field()
    dailyLiquidity = Field()
    dividend = Field()
    dividendYield = Field()
    dividendYieldThreeMonthsAccumulated = Field()
    dividendYieldSixMonthsAccumulated = Field()
    dividendYieldTwelveMonthsAccumulated = Field()
    dividendYieldThreeMonthsAverage = Field()
    dividendYieldSixMonthsAverage = Field()
    dividendYieldTwelveMonthsAverage = Field()
    liquidPatrimony = Field()
    patrimonyValue = Field()
    patrimonyValueByPrice = Field()
    dividendYieldPatrimonyValue = Field()
    physicalVacancy = Field()
    financialVacancy = Field()
    activeQuantity = Field()
